### ISSUE TITLE
add form to add new recipes (200 pts)

### ISSUE THREAD

**Issue by rphammy** [ucsb-cs56-webapps/ucsb-cs56-scrapstosnacks#12]
Add a form page that allows the user to add a new recipe to our database of recipes.
User should be able to type in the recipe name, and the ingredients in that recipe.
When submitted, the website will go to the "Display All Recipes" page, which should have that new recipe on it.

**Comment by wilsonmui** [comment]
This recipe will be entered onto the apps database. After submitted, the database should be updated with this new recipe.

200 pts

**Comment by wilsonmui** [comment]
DONE
