### ISSUE TITLE
create a database for recipes (400 pts)

### ISSUE THREAD

**Issue by rphammy** [ucsb-cs56-webapps/ucsb-cs56-scrapstosnacks#13]
The database should be deployed.
We should be able to access the database and store recipes into it.
When someone adds a recipe, you can see the recipe on the database.
Recipes should stay inside the database after someone creates and submits a new recipe.

**Comment by wilsonmui** [comment]
This should be a RECIPE database, so the database should be arranged properly to store a list of recipes. (A list of 'recipes' where each 'recipe' contains subfields you choose to include like ingredients, images, etc.)

400 pts

**Comment by wilsonmui** [comment]
DONE
