### ISSUE TITLE
Create "Search" Page (200 pts)

### ISSUE THREAD

**Issue by rphammy** [ucsb-cs56-webapps/ucsb-cs56-scrapstosnacks#14]
This page should display a list of basic cooking ingredients, by food group.
Next to each ingredient should be a checkbox that the user can click.
Once the user has clicked the ingredients they want, they can press a "Search" button that will then take them to another page that displays the recipes that correspond to the ingredients inputted.

**Comment by wilsonmui** [comment]
This will bring back the corresponding recipes from the database.

200 pts

**Comment by wilsonmui** [comment]
DONE
